# Basic Site Settings
title: "Varun Khanna"
name: "Varun Khanna"
description: "Data Science Portfolio"
url: "https://discoverdata.github.io"

# Theme
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "air"

# Author
author:
  name      : "Varun Khanna"
  avatar    : "/images/bio-image.jpg" # optional, remove if no image
  bio       : "Data Scientist | NLP | Generative AI"
  location  : "Adelaide, SA"
  github    : "discoverdata"
  linkedin  : "varun-khanna-68802518"

# Social links (will show up as icons if supported)
social:
  type: Person
  name: "Varun Khanna"
  links:
    - "https://github.com/discoverdata"
    - "https://www.linkedin.com/in/varun-khanna-68802518"

# Plugins (keep only essentials)
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
